version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install pyinstaller

  build:
    commands:
      - pyinstaller --onefile flappy_bird.py
      - echo "Build completed"

artifacts:
  files:
    - dist/flappybird.exe
  discard-paths: yes
